name: Community Impact Real Estate
locales: [en]
domains: [www.communityimpactrealestate.ca, communityimpactrealestate.ca]
timezone: UTC
seo_title: 'Community Impact Real Estate Society '
meta_keywords: Community Impact Real Estate Society, Impact Real Estate, Social Enterprise,
  Non-Profit, Community, Social Value, Social Impact, Impact Hiring
meta_description: Community Impact Real Estate contributes to the efforts of building
  an inclusive local economy by using the space in our portfolio to provide affordable
  goods, services, social service support and employment opportunities for the residents
  in the communities within which we work.
robots_txt: ''
asset_host:
metafields:
metafields_ui: {}
sections_content:
